#!/usr/bin/bash

TO="basilfaboya@gmail.com"

function check_memory_usage(){
    echo ""
    echo "memory_usage"
    free ""
    echo ""
}


check_memory_usage >> /home/vagrant/mail/memory-file

echo |sendmail $TO < memory-file
